config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :articles do
    get :article_by_category, on: :member
  end

  resources :comments

  resources :careers

  resources :dashboard do
    get :admin_menu, on: :collection
  end

  root :to => "dashboard#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, :as => :commentable

  belongs_to :user
  belongs_to :category

  has_attached_file :image, styles: { medium: "740x740>", thumb: "100x100>" }, default_url: "/1122133.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  attr_accessible :title, :body, :user_id, :category_id, :image

  accepts_nested_attributes_for :comments

end

app/models/career.rb
class Career < ApplicationRecord
  has_many :key_qualifications

  attr_accessible :title,
                  :description,
                  :education,
                  :key_qualifications_attributes

  accepts_nested_attributes_for :key_qualifications
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles

  validates :title, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, :polymorphic => true

  belongs_to :user
end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user

  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/key_qualification.rb
class KeyQualification < ApplicationRecord

  belongs_to :career

  attr_accessible :body,
                  :career_id

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :articles
  has_many :comments

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def ensure_signup_complete
    # Ensure we don't go into an infinite loop
    return if action_name == 'finish_signup'

    # Redirect to the 'finish_signup' page if the user
    # email hasn't been verified yet
    if current_user && !current_user.email_verified?
      redirect_to finish_signup_path(current_user)
    end
  end

  def new_session_path(scope)
    new_user_session_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  ActionController::Parameters.permit_all_parameters = true

  before_action :find_article, only: [:update]

  def update
    @article.comments.create(params[:article][:comment])
    redirect_to :back
  end

  def create
    Article.create(params[:article]) unless detected_virus?
    redirect_to :root
  end

  def article_by_category
    @categories = Category.all
    @articles = Category.find(params[:id]).articles
    respond_to do |format|
      format.js
    end
  end

  private

  def detected_virus?
    # https://github.com/franckverrot/clamav-client
    client = ClamAV::Client.new
    io = StringIO.new(params[:article][:image].tempfile.read)
    raise "detected virus" if client.execute(ClamAV::Commands::InstreamCommand.new(io)).virus_name.present?
  end

  def find_article
    @article = Article.find(params[:id])
  end

end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  ActionController::Parameters.permit_all_parameters = true

  def index
    @careers = Career.all
  end

  def show
    @career = Career.find(params[:id])
  end

  def create
    Career.create(params[:career])
    id = Career.last.id
    redirect_to career_path(id)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @categories = Category.all
    @articles = Article.all
  end

  def admin_menu
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # binding.pry
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/articles/article_by_category.js.erb
 $("#articles").html("<%= escape_javascript(render partial: 'dashboard/articles', locals: { articles: @articles } ) %>");

app/views/careers/index.html.haml
.container
  .row
    .col-md-8.career
      %strong #{Faker::Lorem.paragraph}
      %h4.career-title Job Title
      - @careers.each do |career|
        %ul
          %li
            = link_to career.title, career_path(career.id)
            %br
            = truncate(career.description, length: 200)
            %br
            %div.time-ago #{time_ago_in_words(career.created_at)}

app/views/careers/show.html.haml
.container
  .row
    .col-md-8
      %strong #{Faker::Lorem.paragraph}
      %h4.career-title #{@career.title}
      %p Summary
      = truncate(@career.summary, length: 1000)
      %br
      %br
      %p Responsibilities:
      %ul
        - @career.key_qualifications.each do |key|
          %li
            = key.body
      %p Description
      = truncate(@career.description, length: 1000)
      %p Education
      = truncate(@career.education, length: 1000)
      %div.time-ago #{time_ago_in_words(@career.created_at)}

app/views/dashboard/_articles.html.haml
- @articles.each do |article|
  %h2.title #{article.title}
  %p.date Posted on #{article.created_at.strftime("%Y-%m-%d")} • #{article.comments.count} Comments
  %br
  = image_tag article.image(:medium)
  %br
  %br
  #{article.body}
  %nav.primary
    %ul
      %li
        %a{"data-toggle" => "tab", href: "#"}  #{article.comments.count} Comments
      %li
        - if current_user
          #{current_user.email}
        - else
          %a{"data-toggle" => "tab", href: "#" } #{Faker::Name.name}
      %li
        - if current_user
          = link_to "Logout", destroy_user_session_path, "method"=>"delete"
        - else
          %a{"data-toggle" => "modal", "data-target" => "#loginModal", href: "#"} Login
  %div.comment
    %ul
      - article.comments.each do |comment|
        %li
          = comment.body
          %div.time-ago-comment #{time_ago_in_words(comment.created_at)}

      %div
        - if current_user.present?
          = simple_nested_form_for article do |f|
            = f.simple_fields_for :comment do |comment|
              = comment.input :body, as: :text, label: false, :input_html => { 'rows' => 4, 'cols' => 80, style: "width: 100%;" }
              = comment.hidden_field :user_id, value: current_user.id
            = f.button :submit, 'Add comment', class: 'btn btn-success', id: 'add_comment'

app/views/dashboard/admin_menu.html.haml
.container
  .card.card-block
    %p.card-text Due ot flexbox's nature, columns in bootstrap-flex are always the same height - that of the column with most content.
  .row
    .col-xs-8.offset-xs-2
      %ul.nav.nav-pills
        %li.nav-item
          %a.nav-link.active{"data-toggle" => "tab", href: "#career"} Career
        %li.nav-item
          %a.nav-link{"data-toggle" => "tab", href: "#article"} Article

      .tab-content
        #career.tab-pane.fade.in.active
          = simple_nested_form_for Career.new do |f|
            = f.input :title, label: 'Title'
            = f.input :description, label: 'Description'
            = f.input :education, label: 'Education'
            = f.fields_for :key_qualifications do |key|
              = key.input :body, label: 'Qualification'
              = key.link_to_remove "Remove qualification"
            = f.link_to_add "Add qualification", :key_qualifications
            = f.button :submit, 'Add opportunity', class: 'btn btn-success btn-opp'

        #article.tab-pane.fade
          = simple_nested_form_for Article.new do |f|
            = f.input :title, label: 'Title'
            = f.input :body, label: 'Body'
            = f.hidden_field :user_id, :value => current_user.id
            = f.input :category_id, collection: Category.all, selected: 1
            = f.input :image, label: false
            = f.button :submit, 'Add article', class: 'btn btn-success btn-opp'
      = link_to "home", root_path(), class: 'homepage'

app/views/dashboard/index.html.haml
.container
  .card.card-block
    %p.card-text Due ot flexbox's nature, columns in bootstrap-flex are always the same height - that of the column with most content.
  .row
    .col-xs-3
      %div
        #{Faker::Lorem.word.capitalize}
        %br/
        #{Faker::Lorem.paragraph}
        %nav.main
          %ul
            - @categories.each do |category|
              %li
                = link_to category.title, article_by_category_article_path(category.id), :remote => true

        %nav.main
          %ul
            %li.career_link
              = link_to "Careers", careers_path()
            - if current_user
              %li
                = link_to "Admin menu", admin_menu_dashboard_index_path()

    .col-xs-8#articles
      = render 'articles', articles: @articles

  / Modal
  #loginModal.modal.fade{:role => "dialog"}
    .modal-dialog.modal-sm
      / Modal content
      .modal-content
        .modal-header
          %button.close{"data-dismiss" => "modal", :type => "button"} ×
          %h4.modal-title Login
        .modal-body
          = form_tag session_path(:user) do
            = text_field_tag 'user[email]', nil, placeholder: 'username'
            = password_field_tag 'user[password]', nil, placeholder: 'password'
            / = check_box_tag 'user[remember_me]'
            / = label_tag 'user[remember_me]', 'Remember me'
            %button.login login
            %br
            / = link_to "Forgot your password?", new_password_path(:user)
          = link_to "Sign in with Facebook", user_facebook_omniauth_callback_path(), id: "sign_in"
        .modal-footer
          / %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>